### ISSUE TITLE
Cannot npm install the library

### ISSUE THREAD

**Issue by hoto** [node-fetch/btoa-lite#1]
**Describe the bug**
Hi, the `npm install @node-fetch/btoa-lite` returns 404. 

I'm guessing the npm project is private and has to be made public in order for the install to work?

**To Reproduce**

1. Run `npm install @node-fetch/btoa-lite`
2. See error
3. The module is not installed

**Expected behavior**
Installs the module.

**Screenshots**
![image](https://user-images.githubusercontent.com/3105832/184553154-3e0cc0d7-34dd-4d79-84cb-079ca0320daa.png)

MacOS, npm version 8.11.0

**Comment by Richienb** [comment]
We've been coping

https://github.com/hughsk/btoa-lite/pull/3#issuecomment-670592736

**Comment by Richienb** [comment]
Somehow got the org

**Comment by Richienb** [comment]
[`v1.0.0`](https://github.com/node-fetch/btoa-lite/releases/tag/v1.0.0) published!
